### ISSUE TITLE
Container dimension issues: centered on top left corner, overflow

### ISSUE THREAD

**Issue by larissa-n** [vasturiano/react-force-graph#118]
Two issues I'm encountering with canvas size and dimension props:

1) If width/height props change, canvas doesn't update. Responsive components, useEffect hooks, etc - won't do it. So whenever I set width and height with variables, the graph is centered on the top left corner. How can I fix that?

2) If the canvas ends up being smaller than the graph, there is overflow. Is there a way to assign a negative charge to the canvas boundaries, or set the zoom such that the entire chart fits? (I rely on a node charge of -200 to limit link overlap).

Codesandbox: https://codesandbox.io/s/force-graph-2d-responsive-eoxu3

Thank you!

![image](https://user-images.githubusercontent.com/37840830/65259387-92a84780-dad2-11e9-8494-fbadbbb0790f.png)

**Comment by vasturiano** [comment]
Thanks for reaching out @larissa-n. 

1. You're experiencing this issue because you're passing `undefined` to the `width` and `height` properties on the first render. `undefined` is not an accepted value for those props, you should make sure that you always include a value, or not set those props to allow fallback to defaults.
I've fixed the sandbox example, just by setting 
```  const { width = 0, height = 0 } = props;```
https://codesandbox.io/embed/force-graph-2d-responsive-3tzz9

2. I would suggest using `ref.zoom(<num>)` to set your desired zoom level for your data. By default the zoom is set to a value inversely proportional to the amount of nodes in the system, but it does not take the canvas size into account.
If you need a dynamic solution, you could read all the nodes `x,y` positions to figure out the extent of the bounding box that fits all the nodes, and then set the zoom level to the value that fits those dimensions into the current canvas size.

**Comment by larissa-n** [comment]
Awesome! Thank you.
