### ISSUE TITLE
Clickable area of nodes does not line up with the visual representation when width/height is changed

### ISSUE THREAD

**Issue by Lander37** [vasturiano/react-force-graph#119]
**The clickable area for each node does not line up with its visual representation when I specify a width and height for the graph.**

i.e.
<ForceGraph2D
    graphData ={this.props.graph_data}
    linkDirectionalArrowLength={8}
    linkDirectionalArrowRelPos={1}
    linkCurvature={0}
    linkLabel={() => ""}
    nodeVal={12}
    nodeCanvasObject={...}
    linkCanvasObject={...}
    dagMode="td"
    dagLevelDistance={100}
    onNodeClick={this._handleNodeClick}
>

This works fine, but once I add in width={800} and height={600} the clickable areas of each node are inaccurate.

Could use some help. Thanks!

**Comment by vasturiano** [comment]
@Lander37 it's difficult to say just from your code fragment. Could you create a minimal example on https://codesandbox.io/ that reproduces the issue?

**Comment by Lander37** [comment]
@vasturiano 

I've made an example here: https://codesandbox.io/s/intelligent-mccarthy-gfd4p

Removing width={400} allows the onClick function for the nodes to be called. But once I specify the width, it doesn't work

**Comment by vasturiano** [comment]
@Lander37 thanks for making that example.
This is happening because you're using `text-align: center` to center align a block. This css property is only advised for text elements, not block elements.

If you choose a different centering method you'll see that positions are correctly detected, for example with flexbox:
```
.App {
  font-family: sans-serif;
  display: flex; 
  justify-content: center
}
```

**Comment by Lander37** [comment]
@vasturiano Thanks for that! Did not realize it was the CSS that was causing it. 

I have a question now regarding replacing the node with some text. I've looked at the examples but can't find the solution to my problem.

I want to replace the circular node with my own node object (A rectangle with text inside). I am able to do this following the example regarding replacing nodes with text using NodeCanvasObject.

A simple example is here: https://codesandbox.io/s/awesome-jennings-qy8r0

The problem is that the clickable area of the nodes still correspond to the original circular node size, which setting nodeCanvasObjectMode to "before" shows. 

How do I make the clickable area correspond to the rectangle in my nodeCanvasObject?

**Comment by vasturiano** [comment]
@Lander37 the short answer is that it's not currently possible. It's a limitation of the library due to the way pointer interactions are handled in the canvas. You can control the size of the (invisible) circle that defines the trap area for pointer interactions, using `nodeVal`. But you can't change the shape of the trap into something else, like your custom node's shape.

The long answer is that the HTML element where the nodes are drawn is a [2D canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API). While this is better than SVG performance wise, it makes interaction handling more difficult. To make it work, a separate (shadow) canvas is used in which each node is assigned a unique color and drawn with it, so that at each mouse pointer movement the node can be determined simply by doing a reverse lookup of the color directly under the mouse pointer. This uses [canvas-color-tracker](https://github.com/vasturiano/canvas-color-tracker) to index the node/link objects by their color. 

The issue when using a customly drawn node, is that the consumer is in full control on how the elements are drawn, and that is opaque to the library itself. In other words, it is unable to separate shape from color. That leaves no option but to draw the items in the shadow canvas with their default shape so the color can be controlled. 

This is the sole reason why the pointer interaction areas have a different shape than the custom nodes. I suggest to calibrate the `nodeVal` of each node so that it's shape approximates the circular area of the invisible node as close as possible.

**Comment by Lander37** [comment]
@vasturiano Okay thanks alot, will close this issue.
