### ISSUE TITLE
Uses GPU resources even when engine is frozen

### ISSUE THREAD

**Issue by ProfessorX737** [vasturiano/react-force-graph#148]
By the time the cooldown time runs out the graph is still using as much GPU as when its running.
It seems the only way to stop GPU usage is to pauseAnimation()

It can be seen from other examples that use d3 by itself does not have this issue like [here](https://bl.ocks.org/steveharoz/8c3e2524079a8c440df60c1ab72b5d03)

Follow steps to reproduce:
1. open [your text demo](https://vasturiano.github.io/react-force-graph/example/text-nodes/index-2d.html) in your browser
2. open task manager side by side and check that the GPU usage is the same even when the engine is frozen.
3. repeat for pure d3 [example](https://bl.ocks.org/steveharoz/8c3e2524079a8c440df60c1ab72b5d03) and check that it does not have this issue

Desktop
 - OS: Windows 10
 - Browser: Google Chrome 79.0.3945.117 (Official Build)

**Comment by vasturiano** [comment]
@ProfessorX737 thanks for reaching out.

The example you mentioned uses `svg` as the rendering platform. The 2D version of this library uses `canvas` instead, which makes it not a direct comparison. Basically, in the `canvas` method there is a continuous clearing and painting of the viewport that carries on even after the force directed engine has stopped. This is so that other features like zoom and node dragging keep on working. There is a deeper discussion of this subject in this `force-graph` module issue, if you're interested: https://github.com/vasturiano/force-graph/issues/75

**Comment by ProfessorX737** [comment]
Thanks for the quick reply, I managed to get something working along the lines of:
```
this.graph.addEventListener("mousemove", (event) => {
   this.fg.resumeAnimation()
   clearTimeout(this.pauseTimeout)
   this.pauseTimeout = setTimeout(()=>{this.fg.pauseAnimation(); console.log('paused')}, 2000)
})
```
