### ISSUE TITLE
nodeThreeObject has to be a Mesh

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#171]
If I want to return a THREE Group, how can I handle it?
My group has some meshes. For example, one of them for an outline and another one is the main mesh.
![image](https://user-images.githubusercontent.com/23615115/79766728-08a6b280-8331-11ea-9256-669fa87dea1e.png)

**Comment by MaksZhukov** [comment]
![image](https://user-images.githubusercontent.com/23615115/79766896-3e4b9b80-8331-11ea-85c6-4d261be4d38e.png)
![image](https://user-images.githubusercontent.com/23615115/79766931-4e637b00-8331-11ea-9043-7e2ba21be1c4.png)

**Comment by vasturiano** [comment]
@MaksZhukov a Three Group is an instance of Object3D so you should be able to use it as an object type returned by `nodeThreeObject`.

The code portion you mentioned above should only be applicable to the built-in object types.

If you're still getting the error would you mind doing a minimal example on https://codesandbox.io/dashboard/recent

And are you extending or replacing the current object (`nodeThreeObjectExtend`)?

**Comment by MaksZhukov** [comment]
https://codesandbox.io/s/react-force-graph-jbdx5?file=/src/App.js

**Comment by MaksZhukov** [comment]
Also dragging doesn't work when you return Tree Group

**Comment by MaksZhukov** [comment]
![image](https://user-images.githubusercontent.com/23615115/79862885-714c6880-83df-11ea-9b71-946dcf250c08.png)
This function recreates `material `and `geometry` on default for objects which were not updated

**Comment by vasturiano** [comment]
@MaksZhukov thanks for putting together the example and surfacing this issue. There was a bug in the underlying `three-forcegraph` module that was causing this. That is now fixed.

Please try with the latest version of the module and let me know if it solves your issue.

As for dragging groups, that is a known issue. ThreeJS drag can only detect the top object. The best way to handle it is use an invisible mesh instead of a group as parent object, and treat as a drag handle. Like in [this example](https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L21-L32).

**Comment by MaksZhukov** [comment]
@vasturiano Thank you! It solves my issue!
