### ISSUE TITLE
link material prop has MeshBasicMaterial instead of MeshLambertMaterial

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#173]
![image](https://user-images.githubusercontent.com/23615115/80004547-214ad000-84cb-11ea-8f58-1bf0939e426b.png)
https://codesandbox.io/s/react-force-graph-jbdx5?file=/src/App.js

**Comment by vasturiano** [comment]
@MaksZhukov that is intentional. It happens if `linkOpacity={1}` and the `linkColor` has no alpha channel.

**Comment by MaksZhukov** [comment]
@vasturiano I added alpha channel to `linkColor `but it doesn't work,
![image](https://user-images.githubusercontent.com/23615115/80074943-99a8a400-8552-11ea-9463-fc435b83b6ac.png)
https://codesandbox.io/s/react-force-graph-jbdx5?file=/src/App.js

**Comment by MaksZhukov** [comment]
Why does't `linkThreeObjectExtend` prop first parameter in func have __lineObj for first render?

**Comment by vasturiano** [comment]
@MaksZhukov for the first question, `linkColor` is an accessor function, so:
`linkColor={link => 'rgba('255,255,0,0.6)'}`

As for the second question, because the method is invoked precisely before creating/updating the ThreeJS object. Only after object creation the attribute `__lineObj` is attached to the link.

**Comment by MaksZhukov** [comment]
@vasturiano Ok, thank you!
