### ISSUE TITLE
Big data performance enhancement

### ISSUE THREAD

**Issue by Arrow891** [vasturiano/react-force-graph#181]
Hello,
I'd like to present a network with almost 100k nodes with 2D graph in which each node is an image, but when the user has interaction with the graph, it freezes, is there any solution to increase the performance?

**Comment by vasturiano** [comment]
Thanks for your question @Arrow891.

Drawing 100k elements on the browser is always going to be a bit problematic no matter how you approach it, because of the sheer volume of rendering the browser needs to do.
Having said that, here is an example that can handle 74k elements (~6k nodes + ~68k links) with relatively good results: https://vasturiano.github.io/force-graph/example/large-graph/

Usually in these graphs there are many more link elements than nodes, and these constitute the bulk of the rendering effort, so you should check how many links you have in your system to get a better idea of the size of your data set.

Further, there's a few points you can think about for improving the rendering performance:

* Images: you are probably doing image rendering using the `nodeCanvasObject` prop. You should keep in mind this function runs once at every frame for every node. So it's extremely important to keep this method as lightweight as possible. If you're drawing images, the size of the image matters. The larger it is, the more worker the browser needs to do.

* Node grouping: 100k nodes is not only an overload for the browser, but possibly also for the user. If you can think of a way to organize your nodes hierarchically, you can perhaps approach it in a way that only the top layers are rendered initially, and the nested ones expanded by user interaction. Here is an [example](https://vasturiano.github.io/react-force-graph/example/expandable-nodes/) that shows how to do something like that.

* Bypass the build-in animation: for small data structures it's nice to see the graph explode from its initial state (all nodes in center) until it reaches an equilibrium based on the data structure. For larger data structures I find it less important and that phase also imposes a lot of strain on the browser as it attempts to render each frame of the force-engine tick, dramatically slowing down the experience of how long it takes for the graph be ready for the user. You can bypass that phase by setting `warmupTicks` to a number greater than 0, say `100`, and `cooldownTicks` to `0`.

Hope some of these pointers help in your case.

**Comment by Arrow891** [comment]
@vasturiano thanks for the time you have assessed to answer my question comprehensively,  the points that you mentioned are really helpful to achieve the goal, please keep this issue open for now and let me implement an example by considering these notable points and share my experience in case of any progress 🙏

**Comment by Arrow891** [comment]
Well I came up with the idea that the best practice for me is to clustering the graph and expand the parent nodes on click because of the limitations of the browsers in visualizing the myriad data, thanks again for your support.
