### ISSUE TITLE
2D Text nodes not shown when zooming in reaching the maximum

### ISSUE THREAD

**Issue by yunfeijing** [vasturiano/react-force-graph#182]
![bug2](https://user-images.githubusercontent.com/18676002/82114654-74016a00-97a1-11ea-9e0b-0fd1a43ee699.gif)
As shown in the GIF, this problem exists in the demo as well. Text cannot be rendered when zooming closer.

**Comment by vasturiano** [comment]
@yunfeijing thanks for reaching out.

This is an issue that happens when the zoom level (`globalScale`) is too high (as in more than 1000x), and the `fontSize` is set proportional to it, therefore very small.
Things start getting problematic with font sizes less than `0.01px`. Canvas starts having rendering issues at that magnification point. 

I would suggest putting a minimum size for the font of `0.05px` or so in your `nodeCanvasObject` method to prevent this glitch from happening.

**Comment by yunfeijing** [comment]
@vasturiano thanks for the time providing the suggestions.
The problem is indeed with font sizes. However, on my device, the rendering issue happens when the font is less than `0.6` (assuming it's in `px` by default?), so I have put a minimum size of 0.6 and everything is going well now.
