### ISSUE TITLE
edge position does not update for ForceGraphVR in all-modes example

### ISSUE THREAD

**Issue by micahstubbs** [vasturiano/react-force-graph#19]
edge position does not update for ForceGraphVR in all-modes example

it looks like this occurs when
- all three renderers are used on the same page
- data is loaded from a json file (as opposed to being generated with `random-data.js`)

live example to reproduce the issue https://bl.ocks.org/micahstubbs/1d0c15a8dbb33f39b5e2a70e69514712

![edge-position-1](https://user-images.githubusercontent.com/2119400/42117690-f11d2bd0-7bb2-11e8-9d51-6721ba9a3f0c.png)

**Comment by micahstubbs** [comment]
I thought this might be a more general bug with json data and the `ForceGraphVR` renderer, but the standalone `ForceGraphVR` example renders fine.  🤔 

standalone example that works fine https://bl.ocks.org/micahstubbs/61d04ba1e1f5ac9d457ddbcbfaffca18

![screen shot 2018-06-29 at 3 43 51 pm](https://user-images.githubusercontent.com/2119400/42117726-3d8956e2-7bb3-11e8-9f49-d52ae3236529.png)

**Comment by vasturiano** [comment]
Hey @micahstubbs, figured out why this is happening. You're loading the json file once and then feeding the same data structure to the 3 components. That means that the components are sharing the exact same object reference. Since they actually mutate the data object (insert additional x, y, z attributes, etc) they are colliding on updates among each other and getting confused in all sorts of ways. 

You can verify this by dragging a node on the left-most component (`ForceGraph2D`) and seeing that the middle one (`ForceGraph3D`) actually reacts to the node position change (a cool effect by the way, I should remember if I'm ever to build a master/slave graph representation :) ).
The components are sharing the nodes positions. The frozen links on the VR component are just another artifact of the object reference sharing.

So, all that's needed is to make sure the graphs don't interact by supplying them independent data objects. You can simply clone the data by doing:
```
graphData={JSON.parse(JSON.stringify(data))}
```
and you should be golden. 😎

**Comment by micahstubbs** [comment]
hah, you are totally right 😂 

thanks for debugging my javascript.

for completeness, here's the example I asked about, updated with the suggested fix https://bl.ocks.org/micahstubbs/1d0c15a8dbb33f39b5e2a70e69514712

and here's a new example of that fun linked view behavior https://bl.ocks.org/micahstubbs/c88a121c743f382f9a3953f2934b5c3c
