### ISSUE TITLE
Bug: nodeClick after rotation requires multiple clicks

### ISSUE THREAD

**Issue by Kohze** [vasturiano/react-force-graph#198]
**Describe the bug**
Node click event after rotation requires multiple clicks. It seems like the graph itself knows that the node is there, but it takes still a while to actually activate the onClick function (in the example case the zoom into object).  The effect occurs after each move/shift/rotation of the graph. When I keep the graph still, I can click on nodes and the function gets activated after the first click (as expected).

**To Reproduce**
go to
https://vasturiano.github.io/react-force-graph/example/click-to-focus/
rotate the graph, then click on a node. After each rotation, it takes 2-3 clicks to actually trigger the onClick event to zoom into that node. The same behavior we see in our project which makes the graph appear less "responsive" or "buggy". 

**Expected behavior**
Expected behavior would be to directly being able to click on a node and trigger the onClick event/function instead of clicking a few times on the same node.

**Desktop (please complete the following information):**
- windows 10, chrom@latestVersion

**Comment by vasturiano** [comment]
@Kohze thanks for reaching out.

Are you per chance using a three-finger drag trackpad movement to move the camera? 

This is a common reason why for a short period after the drag release, clicks are not available. Some trackpads typically add a 300ms delay after drag release before triggering `pointerup` (which signals the end of the drag interaction), mainly to allow the user to continue the drag motion when briefly lifting the fingers from the trackpad.

You can test that mechanism in this codepen: https://codepen.io/vasturiano/full/PoZebpR

You can also try doing the same using a regular mouse, or a down-press dragging motion on your trackpad, to confirm the root cause of the issue.

**Comment by Kohze** [comment]
working on a PC with mouse, so not trackpad related. The codepen you shared works as expected.

**Comment by vasturiano** [comment]
@Kohze thanks for checking. I dug a little deeper and there was an issue with detecting the end of drag motions during the dampening phase of the trackball controls (after mouse release).

This should now be fixed (from `v1.18.3` of `react-force-graph-3d`) and this example should be functioning properly:
https://vasturiano.github.io/react-force-graph/example/click-to-focus/

Let me know if this solves all the issues on your side.

Thanks!

**Comment by Kohze** [comment]
Solved it, amazing!
