### ISSUE TITLE
Silencing console log

### ISSUE THREAD

**Issue by Jinmo-K** [vasturiano/react-force-graph#206]
Is there any way to silence the console.info("force-graph loading _ nodes _ links") logging ? Seems like it should either not be there at all, or a prop option to silence it.

Thanks!

**Comment by vasturiano** [comment]
@Jinmo-K thanks for reaching out.

The info message is actually intentional, as convenient information about the graph data that is being plotted. It's also not a debugging `console.log` statement, and can be easily filtered out in the browser console if desired.

Is it causing any specific issues that I may not have considered, or is the concern mainly at console "cosmetic" level?

**Comment by Jinmo-K** [comment]
@vasturiano Thanks for the response. Yeah it was a cosmetic issue, mainly that it made it more difficult to see my own debugging statements, but I've already filtered it out so all is well. Mostly was wondering if it might have been unintentional. Thanks!
