### ISSUE TITLE
onNodeClick not working on mobile

### ISSUE THREAD

**Issue by Zhell1** [vasturiano/react-force-graph#216]
**Describe the bug**
I have a forceGraph3d which works very well on desktop, with links when the user clicks on each node. However once I load the page on a mobile the click events don't fire, it will only stop the graph's rotation for as long as it is held down.

**To Reproduce**
As I am using the React version this is how it looks like:
```
var handleNodeClick = function(node){
      console.log("forcegraph click on ",node)
      if(node){
          var newPageUrl = node.link
          window.open(newPageUrl, "_blank") //to open new p
      }
}
```
and

```
<ForceGraph3D graphData={dataSet}
      width={window.innerWidth}
      height={window.innerHeight-55}
      showNavInfo={false}
      forceEngine="d3"
      linkDirectionalParticles={setdirectionallink}
      nodeThreeObjectExtend={false}
      nodeThreeObject={getnodetext}
      nodeAutoColorBy={(node)=>{return node.id}}
      nodeRelSize={4} 
      nodeResolution={16}
      linkOpacity={0.4}
      ref={this.ref_forcegraph}
      enableNodeDrag={false}
      cooldownTime={0}

      onNodeClick={handleNodeClick}
      onNodeHover={increasenodetext}

      warmupTicks={100}
      controlType="orbit"
/>
```

**Expected behavior**
dragging should rotate the graph but clicking on a node should trigger onNodeClick. The solution could also be a way to turn off dragging to replace it only with onNodeClick's behavior

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome -> devtools mobile phone simulator (any)]

**Smartphone (please complete the following information):**
 - Device: [Any mobile phone]
 - Browser [Chrome]

Is this a known issue or is there a fix ? thank you very much

**Comment by sinno666** [comment]
@vasturiano
I have similar trouble with above as well.
When I tried below code on desktop, it worked well, but on a mobile, it doesn’t work well.
After the page loaded, I can rotate the graph at first, but once I click a node, the graph can’t rotate.
(I tried it not only on codeSandbox but also on firebase hosting)
https://codesandbox.io/s/testforcegraph3d-pnk3b?file=/src/App.js

However, I load the below example page on a mobile, it works well without any problem.
https://vasturiano.github.io/react-force-graph/example/forcegraph-dependencies/

I can't understand why that's problem happen even though I use same component(ForceGraph3D).
So, how do I solve this problem? Please guid me.

**Comment by vasturiano** [comment]
@sinno666 I'm so far unable to reproduce your issue. There doesn't seem to be any difference in terms of interaction by comparing those two links. Can you tell me which device/browser you are using?

**Comment by sinno666** [comment]
@vasturiano 
I reproduce the issue in below environment.

**Working fine**
Devise:
--Desktop(Mac OS BigSur, M1 MacBook Pro)
Browser:
--Google Chrome

**Not working fine**
Devise1:
--iPhone12 Pro
Browser:
--Google Chrome, Brave, Safari

Devise2:
--Desktop(Mac OS BigSur, M1 MacBook Pro)
Browser:
--Google Chrome(Device mode: iPhoneX)

Deployed URL:
https://forcegraph3d-test.web.app/
Source:
https://github.com/sinno666/reactforcegraph3d-test
▼Once I click a node, the graph can't rotate.
<img src="https://user-images.githubusercontent.com/39767988/124841214-b0a4ac00-dfc7-11eb-8dd3-14d335f26360.gif" width="200">

**Comment by vasturiano** [comment]
@sinno666 thanks for your detailed report.

After some extended investigation I was able to identify the source of the problem.
This was caused by a combination of the recent upgrade in the `three` repo to migrate Trackball controls to use pointer events (see [PR](https://github.com/mrdoob/three.js/pull/22006)), and the solution to [this issue](https://github.com/vasturiano/3d-force-graph/issues/413) in the `3d-force-graph` repo.

Furthermore, the issue was not visible in this repo's example, because that is using the UMD version of the module, which had `three` `0.129` bundled with, while your CRA was including the latest version `0.130`. This issue was only affecting apps on mobile devices with version `0.130` of `three`.

This should now be fixed if you include the latest version of `react-force-graph-3d` (`1.21.10`).

Thanks again for your report, and let me know if you come across any other issues. 👍
