### ISSUE TITLE
Some example pages are not working 

### ISSUE THREAD

**Issue by NicoEspositoARG** [vasturiano/react-force-graph#222]
Hi! 

I noticed that some of the example links are not working from a few days ago. I tried from different browsers and devices, with similiar results:

[](https://vasturiano.github.io/react-force-graph/example/basic/)

![imagen](https://user-images.githubusercontent.com/46970426/92337672-a224f580-f081-11ea-820a-d23633f1e189.png)

[](https://vasturiano.github.io/react-force-graph/example/large-graph/)

![imagen](https://user-images.githubusercontent.com/46970426/92337806-6d656e00-f082-11ea-800a-7bcea038e37f.png)

Thanks in advance!

**Comment by vasturiano** [comment]
Thanks for the heads up @NicoEspositoARG!

There was an issue with rollup bundling the aframe components. It was affecting only the UMD targets that's why it was only showing up in the browser examples, and slipped by undetected.

Should now be fixed in the latest versions of the components, and the VR examples should be working again. 👍
