### ISSUE TITLE
onNodeCenterHover doesn't work on THREE group as node 

### ISSUE THREAD

**Issue by afermeli** [vasturiano/react-force-graph#240]
Hi, I'm using react force graph vr mode and I'm facing an issue with the "onNodeCenterHover" option of the graph.  The method nodeThreeObject of my graph returns a Three group made of a Sphere and a SpriteText and the onNodeCenterHover doesn't seem to work on groups. Is there a hitbox attribute or anything I can set in order to adapt the onNodeCenterHover to my situation ? Thank you very much

**Comment by vasturiano** [comment]
@afermeli thanks for reaching out.

I think this is related to an historical issue of Three not handling raycasting well within groups. I believe this is already fixed in the latest version of `ThreeJs` but not in the version that `a-frame` uses internally (for the VR rendering). That's why you probably won't experience the issue in the plain `3d` version of the component.

For now, you can get around it by creating a mesh structure as parent that acts as raycaster trap, instead of the Group. Something like this:
```js
nodeThreeObject={node => {
  // use a sphere as a raycaster trap
  const g = new THREE.Mesh(
    new THREE.SphereGeometry(10),
    new THREE.MeshBasicMaterial({ depthWrite: false, transparent: true, opacity: 0 })
  );

  // add all the children
  const sprite = ...
  obj.add(sprite);
  
  return obj;
}}
```

Let me know if this solves it for you.

**Comment by afermeli** [comment]
Hi, you've just solved my problem ! Thank you very much for your help I was totally stuck !
