### ISSUE TITLE
Enable pan but not zoom

### ISSUE THREAD

**Issue by artt** [vasturiano/react-force-graph#261]
Right now it seems like you can enable *both* pan and zoom using `enableZoomPanInteraction`.

I'm wondering if there's a way to enable just pan but not zoom? Basically, I don't like for the users to scroll down (using mouse wheel/trackpad) and suddenly the page stops scrolling and the graph got zoomed instead. So I think I'll add a button for zoom. However, I'd still like for the user to be able to pan around.

**Comment by vasturiano** [comment]
Thanks for reaching out @artt.

It's useful to be able to control the two interaction types separately, so I altered the api so that the previous prop has been split into two: `enableZoomInteraction` and `enablePanInteraction`.

For backwards compatibility the old prop `enableZoomPanInteraction` still works, but may be deprecated in the future.

Upgrade to the latest version to see the changes.
