### ISSUE TITLE
Props for node/link color legends

### ISSUE THREAD

**Issue by Justin-W** [vasturiano/react-force-graph#268]
**Is your feature request related to a problem? Please describe.**
When using the `nodeAutoColorBy` and/or `linkAutoColorBy` properties, it is not obvious what each color means. And a color legend is such a common solution to this common problem, that is seems like it should be a built-in feature/setting of the component, rather than a separate "app-level" add-on.

**Describe the solution you'd like**
It would be nice if the component supported `showNodeColorLegend` and `showLinkColorLegend` props (accepting true/false and/or square/circle/none values) to control whether/how to automatically display color legends within the graph. Or maybe even multiple props to give more control over them, such as `nodeColorLegendType`, `nodeColorLegendPosition`, etc. (similar to how there are multiple, related `linkDirectionalArrow*` props).

**Describe alternatives you've considered**
Since the colors used by the `nodeAutoColorBy` and/or `linkAutoColorBy` properties' functionality are implementation details of this component, building a legend as an app-level add-on (external to this component) would require coupling to the internal implementation of this component, and seems like it would be more complicated than built-in support for the new properties I proposed above.

**Additional context**

See the "swatches" section here:
https://observablehq.com/@d3/color-legend

And the "categorical legend" examples here:
https://www.d3-graph-gallery.com/graph/custom_legend.html

And the legend in this example:
https://observablehq.com/@d3/mobile-patent-suits

**Comment by Justin-W** [comment]
@vasturiano P.S. Fantastic component! Great job! Thanks for creating it! :)

**Comment by vasturiano** [comment]
@Justin-W thanks for reaching out.

Since there are so many third party components out there that implement color legend UIs, it would seem a bit over the top to reinvent the wheel inside this component. Also, because every use case would probably ask for a different legend styling, and that can easily snowball the component api with props unrelated to its core functionality. 

You can look at [d3-legend](https://d3-legend.susielu.com/), that's a super nice and well-thought of legend component.

In addition, you can always extract the colors automatically assigned to the nodes/links by looking in the `graphData` structure that you input to the component. Each node/link will have a `color` attribute storing the color that was automatically assigned.

Also, I should mention that the automatic color assignment should only be used for the simplest of cases as it gives you minimal control over the process. It's just a convenience method for a quick setup. For anything requiring more control and customization I'd suggest to use the `nodeColor`/`linkColor` accessor methods.

**Comment by Justin-W** [comment]
OK, I'll try that. Thanks for the tips.

**Comment by mritunjaymusale** [comment]
@Justin-W  did you manage to get it working? Also were you able to do the same for ForceGraph3D ?
