### ISSUE TITLE
How to use just the graph visualisation without the force engine?

### ISSUE THREAD

**Issue by aleksabobic** [vasturiano/react-force-graph#272]
Hi, first of all fantastic library, really appreciate your work! :) 

I would like to pre-compute my graph layout on the backend (using a different language and approach due to a large volume of data) and just render the nodes on the frontend. I setup a demo project with mobx and react and tried setting the cooldownTime to 0 and pausing the animation in order to disable the force engine, however when inspecting my state, I can still see the values of the nodes being changed (specifically fx,fy,fz are being set to 0 and the values are being applied to x,y,z and then back to fx,fy,fz).

Is there a way to prevent these changes? I assume there shouldn't be a need to modify the data any further if I provide all the requried parameteres inside of my nodes.

Sorry if this is a basic question but I tried looking through your projects and existing issues and couldn't find anything similar. I'm noticing a huge performance drop at already 10k nodes but when I run your 75k node demo it runs fluently so I'm clearly doing something wrong. 

Thank you in advance!

**Comment by vasturiano** [comment]
@aleksabobic thanks for reaching out.

All you should need to do is fix your nodes by setting `fx`, `fy` and `fz` attributes on them. This tells the component to use that for positioning instead of the force engine generated positions.

Further, since you don't need the force engine at all, you can disable its iteration cycles by setting `cooldownTicks={0}`. This will improve the performance.

If you're still having issues, can you make a quick reproducing example on https://codesandbox.io/, so we can debug further?

**Comment by aleksabobic** [comment]
Hi @vasturiano thanks for the prompt reply! 

Your change suggestions helped with the performance! I can render graphs with 50k nodes and 50k edges now (which is understandably slow).
