### ISSUE TITLE
Does d3Force interfere with dagMode?

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#281]
**Describe the bug**

I am trying to add dagMode in an app using react-force-graph, with the react-dat-gui to make a control menu
The higher order component I have written uses the `d3Force` method to adjust the 'link', 'charge' ( `d3Force={() => {('charge').strength(-75).distanceMax(100)}}`) and 'center' forces, and 
add a 'radial' force. 
`dagMode` doesn't work and I wanted to just hear whether changing and adding d3Forces prior to activating dagMode could cause it.

**To Reproduce**
1. Initialise a 2D graph, set `d3Force={() => {('charge').strength(-75).distanceMax(100)}}`
2. Maybe add radial force, tweak center and link forces
3. pass `dagMode="lr"` or another valid value

**Expected behavior**
Graph layout changes to dag mode

**Screenshots**
![forcegraph](https://user-images.githubusercontent.com/30726223/116118124-487b4500-a6bd-11eb-9b1d-59eaa77e5777.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 
 - Version: react-force-graph@1.40.5

**Comment by vasturiano** [comment]
@JonThom The `dagMode` and forces available in the system should be independent to some degree. At least in the sense that one should not break the other.
What happens when you use a DAG mode is that it will fix the nodes positions across one dimension, for example if you set `td` it will fix the `y` coordinate of nodes into layers. The `x` dimension is in this case free flowing and determined by the interaction of whichever forces are present in the system. 
So if you set both `dagMode="lr"` and some other custom force, the additional force will only be used to dynamically adapt the nodes positions along the `y` axis, since the `x` axis will be pre-fixed.

Hopefully that answers your question.

I also noticed that you're using `d3Force` as a prop. This should be used as a component method (via the component forward ref), not a prop. See this example for details:
https://github.com/vasturiano/react-force-graph/blob/6da855e75a61c670d6e101f8f48554d5e6385d67/example/collision-detection/index.html#L26-L34

**Comment by JonThom** [comment]
@vasturiano I appreciate your advice, it eliminates a lot of possible causes!

Also, lucky that I sent that snippet with using the d3Force as a prop, that's already something to fix.

Best wishes
