### ISSUE TITLE
Docs: README states that d3AlphaMin defaults to 0, when in fact it defaults to 0.001

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#289]
**Describe the bug**
README states that d3AlphaMin defaults to 0, when in fact, according to https://github.com/vasturiano/d3-force-3d#simulation_alphaMin, alphaMin defaults to 0.001

**Comment by vasturiano** [comment]
@JonThom that default value is overridden here:
https://github.com/vasturiano/three-forcegraph/blob/599ef1e75356ff2c111b570f2f5193d81bb95836/src/forcegraph-kapsule.js#L159

Because the normal way in this module to control the simulation runtime is via `cooldownTicks` and `cooldownTime`. But, that value can always be customized via the `d3AlphaMin` prop.

**Comment by JonThom** [comment]
Thank you for clarifying!
