### ISSUE TITLE
After adding a node, it's vx, vy, vz, x, y, z properties will be NaN.

### ISSUE THREAD

**Issue by csansz** [vasturiano/react-force-graph#301]
Hi!
After adding a node to my data object, all of the new node's and it's parent's vx, vy, vz, x, y, z properties changes to NaN.
So they won't appear on the canvas, however if I check the console, their datas are in the data object.

```
const addNode = (node) => {
      const { nodes, links } = data;
      const id = nodes.length;
      var node2add = { id: id, label:"test" };
      var link2add = { source: node, target: node2add };
      nodes.push(node2add);
      links.push(link2add);
  };
```

```
id: 11
label: "test"
vx: NaN
vy: NaN
vz: NaN
x: NaN
y: NaN
z: NaN
```

**Comment by vasturiano** [comment]
@csansz it's difficult to say without broader context. Could you make a reduced replicating example on https://codesandbox.io?

**Comment by csansz** [comment]
@vasturiano 

Sure, I just created it in codesandbox, on right click on a node you can add or delete a node. 
[https://codesandbox.io/s/goofy-sound-3oex4](url)
In some instances the delete is also works incorrectly, if you could check that also, I'd be very grateful.
Thank you!

**Comment by vasturiano** [comment]
@csansz thanks for making the code sandbox.

I think the issue that you're experiencing is because you're not signalling to the force graph component that the data structure has changed. It's not sufficient to simply internally mutate the data structure, the rendering component needs to know that a change has happened in order to react to it, and perform the necessary adjustments.

You can see in this example how the a new data structure is set to signal a change to the ForceGraph component:
https://github.com/vasturiano/react-force-graph/blob/7c6a34d53234bf860c85fc8c53a40154999d6ff5/example/dynamic/index.html#L43
