### ISSUE TITLE
zoomToFit has >10sec delay when used in React functional component

### ISSUE THREAD

**Issue by MarcGruener** [vasturiano/react-force-graph#303]
First of all, a huuuuge thank you to @vasturiano and all the other contributors.

I am currently trying to use a ForceGraph2D inside a React functional component.
I'd like to use the zoomToFit method but can't seem to make it work as intended.
The goal is to have a similar effect compared to your fit-to-canvas example.

This is what I have so far:

```
function TestGraph() {
    const [data, setData] = useState({ nodes: [], links:[] });


    useEffect(() => {
        const fetchData = async () => {
            const result = await axios(
                'http://127.0.0.1:8000/force-graph/?format=json',
            );
            setData(result.data);
        };
        fetchData();
    }, []);

    useEffect(() => console.log(data))

    const graphRef = useRef();

    return (
        <ForceGraph2D
            ref={graphRef}
            graphData={data}
            backgroundColor={'black'}
            width={1600}
            height={800}
            onEngineStop={() => graphRef.current?.zoomToFit(400, 20)}
        />
    )
}
```

It seems to be working except for the face that there is a delay of >10sec between the graph being rendered and the zoomToFit actually taking place. I'd really appreciate some help with this.

https://imgur.com/a/CoU04yJ

**Comment by vasturiano** [comment]
@MarcGruener thanks for reaching out.

That's probably because your `cooldownTime` (the length of time the force engine takes to stop the engine and freeze the layout) is that long (it defaults to `15s`). You can simply reduce that time if you'd like. Or alternatively reduce the number of ticks via `cooldownTicks`. Whatever elapses first will cause the engine to stop and the `onEngineStop` event to trigger.

**Comment by MarcGruener** [comment]
Oh my gosh, thanks a LOT for your support.
I am just starting out with React and this library is a huge help.
