### ISSUE TITLE
Incorrect xy axis in links

### ISSUE THREAD

**Issue by ImadChughtai** [vasturiano/react-force-graph#358]
**Describe the bug**
Facing issue with x, y of link's nodes.
For example: we have node A. x,y of node A is different in nodes, and x,y of node A in links is different.

**To Reproduce**
I have attached json file of my graph data.

**Expected behavior**
In links nodes' x,y should be same as in nodes array of object.

**Screenshots**
![image](https://user-images.githubusercontent.com/41489373/162737604-88325d22-289e-432c-bbaa-f88b39bf9f3a.png)

JSOB File Link: https://mutualfilesharing.com/UploadedFiles/graphjson.json
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.75

**Comment by vasturiano** [comment]
@ImadChughtai thanks for reaching out.

It looks like the `source` and `target` attributes in your `links` are pointing to objects not in your `nodes` structures. This could happen if you serialize the graph data structure and then feed it back into the library, because the memory pointer references between links and nodes is lot. Though it's hard to say that's what's happening in your case without more context.

**Comment by ImadChughtai** [comment]
Solved the issue by looping through links and assigning source and target ids again.
