### ISSUE TITLE
Question: Is it possible to specify link width for individual links, such that the width changes when zooming in and out.

### ISSUE THREAD

**Issue by andrea-lam** [vasturiano/react-force-graph#359]
This is a question for the 2d and 3d force graphs. 

At the moment, I am specifying the link width for each individual link using the linkWidth property: 
`linkWidth = {(link) => link.linkWidth}`
, where link.linkWidth is an integer. This does specify the link width, but the width doesn't change with the diagram when I zoom in and out. Is it possible to have the linkWidth change with the diagram? (E.g. specify the width as a percentage of the node diameter.)

Thank you!

**Comment by vasturiano** [comment]
@andrea-lam thanks for reaching out.

As mentioned in [the docs)(https://github.com/vasturiano/force-graph#link-styling) for `force-graph`, the link lines are intentionally setup in a way that the width remains constant across zoom levels, otherwise they tend to disappear or become too jarring when close.

>  Keep in mind that link widths remain visually contant through various zoom levels, where as node sizes scale relatively.

This is particularly true in the 2D mode. In 3D you can set different scalable widths which will generate "tube-like" 3d objects which will appear larger when closer to the camera.

**Comment by andrea-lam** [comment]
Hi @vasturiano, thank you for your reply!
