### ISSUE TITLE
Can't import ForceGraph3D in an a-frame application

### ISSUE THREAD

**Issue by squanchd** [vasturiano/react-force-graph#36]
It seems like the THREE imports are clashing when I import  ForceGraph3D from react-force-graph into an existing AFrame application (which has its own THREE dependency).

``` 
NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'a-node'. A type with that name is already registered.
```
Is there a way around this issue?

**Comment by vasturiano** [comment]
Hmm, this is probably because `react-force-graph` already brings its own version of `a-frame` (for the VR mode), and apparently "there can be only one" instance in an app.
Have you considered using the [aframe-forcegraph-component](https://github.com/vasturiano/aframe-forcegraph-component) directly, instead of this react wrapper?
