### ISSUE TITLE
Painting Over Links

### ISSUE THREAD

**Issue by GeoffGodwin** [vasturiano/react-force-graph#40]
nodeCanvasObject is excellent for allowing custom painting code over nodes on the graph. Is it possible to also expose a similar method to draw over links?

**Comment by vasturiano** [comment]
@GeoffGodwin I think that would be a good feature addition. It's slightly more complicated because the method would have to read the `source`/`target` coordinates and draw it in the correct location, so it puts more burden on the client implementation.
But I still think it would be useful. I'll leave the issue open until there's a bit of time to implement it. Or I'll accept a PR too if you have something working. :)

**Comment by GeoffGodwin** [comment]
Yeah I may have to give that a try. I figure getting the midpoint between source and destination is easy enough for straight links. Slightly more work to calculate the curved links but not terrible in terms of the price of the calculations. If I get a chance I'll open a PR with whatever I come up with. Thanks!

**Comment by qasimalbaqali** [comment]
@GeoffGodwin Have you got the chance to try it out? I currently have a use case where I would like to paint the links of the selected node.

**Comment by vasturiano** [comment]
@GeoffGodwin @qasimalbaqali this is now already supported, using `linkThreeObject` and `linkPositionUpdate`.
