### ISSUE TITLE
Solid background behind text node

### ISSUE THREAD

**Issue by obrunodelgado** [vasturiano/react-force-graph#426]
Hello guys, how are you? First of all, congratulations for the amazing tools that you are building. The results are really impressive.

I've built [this site](https://cosmovisao.online/)  using react-force-graph and SpriteText, following [this sample ](https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-3d.html) available at react-force-graph repository.

But as you can see in the site or in the image below, even if I set the backgroundColor property of the TextSprite, the link lines is in front of the Sprite, making it difficult to read the word.

![image](https://user-images.githubusercontent.com/2372140/221140809-2c75da26-5086-4dd9-af25-d46e7b2868bb.png)

Could you please help me figure out how can I make the TextSprite to be in front of the links?

**Comment by vasturiano** [comment]
@obrunodelgado thanks for reaching out.

I'm not sure what you're suggesting makes absolute sense from a spatial perspective, nor if it's actually possible. The reason why the lines (at least portions of) show in front of the node objects (Sprite) is because those points are actually closer to the camera. The 3D rendering just follows what would be expected in a real scenario, which is the lines being visible because they're "in front" of the labels.

**Comment by obrunodelgado** [comment]
Makes sense.
