### ISSUE TITLE
react 3d force graph can't set both link curvature and width

### ISSUE THREAD

**Issue by bt2414** [vasturiano/react-force-graph#48]
```
        <ForceGraph3D
          ref={el => { this.fg = el; }}
          graphData={this.props.GraphReducer}
          linkWidth={3}
          linkCurvature="curvature"
        />
```
The linkCurvaure will be disabled if I set linkWidth. If I delete linkWidth, the Curvature will work.

**Comment by vasturiano** [comment]
@bt2414 thanks for the report. Unfortunately that is a known limitation of `linkCurvature`, it only works for line geometries (`linkWidth` set to default). The root cause is that the shape of [TubeGeometries](https://threejs.org/docs/#api/en/geometries/TubeGeometry) cannot easily be updated and objects would need to be constantly removed and recreated, which would impose performance issues to the engine.
