### ISSUE TITLE
Is there anyway to prevent hovering over nodes from moving them

### ISSUE THREAD

**Issue by kkacquah** [vasturiano/react-force-graph#62]
My graph is very stretched, so these small movements make the graph move violently. I would like to use "onHover" and "onClick" to trigger actions in other components, but these small movements make the graph on usable. Is there anyway to only enable onHover callback functions I specified?

This library has been extremely helpful for helping my understand network data I am working with currently, I am very grateful!

**Comment by vasturiano** [comment]
@kkacquah hovering or clicking interactions on the nodes should not cause them to move. The only interaction I can think that causes that are the node drags (for which you need to hold-click and move the mouse). Perhaps those are being accidentally triggered in your case? 
Also, if you don't need it, you can disable the node drag interactions by setting `enableNodeDrag={false}`.

**Comment by qasimalbaqali** [comment]
I noticed that whenever I use `setState` the graph moves, so I am guessing because of re-rendering. I have a mouseover event on a div that wraps the graph component, and im setting the x and y positions of the mouse. So whenever the user moves the mouse, there would be a movement of the graph. 

Would pausing and then resuming the animation fix this you would think? Would it be a good idea?

**Comment by jhaenchen** [comment]
I'm experiencing this issue as well in VR mode. Whenever I hover the whole graph moves. I'm calling setState but I'm not modifying anything sent to the graph component.
