### ISSUE TITLE
turn off double-click zoom

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/react-force-graph#68]
Hey! Just wanted to say that this library is amazing. I've been super happy with it except for a few minor issues, one of which has to do with zooming and double-clicking.

Is there a way to turn off zooming on double-click without completely turning off zooming and panning?

I've added an action that takes place when a user double-clicks on a node, so having it zoom in also leads to issues.

The only way I've found so far is to set `enableZoomPanInteraction = false`, but I would rather not have to completely rebuild the zoom/pan features as I need them in my application, and they work exactly how I would expect them too except for the double-click.

Thanks!

**Comment by vasturiano** [comment]
Glad the lib is useful! You raise a good point about the double-click behaviour. I suppose you're referring to the 2D mode, right?
I don't think the current "double-click to zoom" behaviour was ever intentional, but an artifact imported from `d3-zoom`. As such, I've removed it so it shouldn't zoom on `dblclick` any longer, if you take the latest version (`1.5.4`).

Let me know if it solves it for you.

**Comment by SZBoatwright** [comment]
It solved it, thanks!
