### ISSUE TITLE
Loading in links when target nodes don't yet exist

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/react-force-graph#84]
# problem
I'm loading data in from a very large database (millions of nodes/links), but I'm only loading in small sections of the database at a time. 

Because of this, many nodes in the database have links attached to them where the target node has not actually been loaded in yet. Optionally, by clicking on a node, linked nodes can be loaded. 

I've found that if I just load in all links attached on a node, the app will crash because the target for the edge doesn't exist, so I have to check if each target node exists before adding a link, and also check if links that were not previously added can be added in every time new nodes are added. 

# the data
the structure of each node object coming in the database looks somewhat like this: 
```javascript
{
	id: '1234',
	type: 'nodeType',
	links: [
		{dest: '5678'},
		{dest: '0345'},
	]
}
```
I've simplified the data quite a bit to make more sense for this example, but the main point is that each node keeps track of its own edges.

# question
Would it be possible to be able to add in links that don't have a source/target node currently loaded in?

**Comment by vasturiano** [comment]
@SZBoatwright the module cannot accept links to non-existing nodes because it can not know how those links are expected to be handled. Throwing an exception is intentional as it surfaces the issue to the consuming app. The best is if you sanitize the data prior to handing it over to the lib, even if it's a partial set. Then you can decide how those cases are handled, either by:
* Excluding those links
* Creating dummy nodes that serve as temporary placeholders
* Fetch the real missing nodes

**Comment by SZBoatwright** [comment]
@vasturiano I'm already filtering out links that don't have all their required nodes, so I'll keep doing that. Just wanted to see if it was possible to load everything in/if I was missing something. Thanks!
