### ISSUE TITLE
Link opacity bug

### ISSUE THREAD

**Issue by Benkevych** [vasturiano/react-force-graph#9]
I have some invisible links, but somehow they appear over other links sometimes. 
Example: http://ec2-52-14-138-28.us-east-2.compute.amazonaws.com/

![screen shot 2018-05-07 at 18 05 35](https://user-images.githubusercontent.com/24266732/39709132-b80096b2-5221-11e8-8abb-45c2d9f0c2c5.png)
 
![screen shot 2018-05-07 at 18 10 19](https://user-images.githubusercontent.com/24266732/39709217-f97adfa8-5221-11e8-8b29-8f89f5e72de6.png)

**Comment by vasturiano** [comment]
Hi @Benkevych, thanks for the report. The visual artifacts you see are due to three.js dificulty with transparent object. Some background here: https://stackoverflow.com/questions/15994944/transparent-objects-in-threejs/15995475#15995475

Long story short, just add `depthWrite: false` to your link custom material and it should fix it.

**Comment by Benkevych** [comment]
@vasturiano well, this is not the best solution, because it results some wierd illusions)
![screen shot 2018-05-08 at 12 32 03](https://user-images.githubusercontent.com/24266732/39749850-61cc7ce8-52bc-11e8-929b-dd40ec67e068.png)

**Comment by vasturiano** [comment]
Yes, it does cause some Escher-like effects, because the depth buffer computation is being bypassed.
This is a hard problem, rooted in three.js and WebGL.

An alternative work-around I would suggest for your case is to simply make your hidden (opacity=0) links as thin as possible (but not 0). Something like:
```
linkWidth={link => isHidden(link) ? 0.01 : normalWidth}
```
This will minimize the visual impact of the gaps, hopefully to a point that is neglectable.
